@NaserPortfolio.Api_HostAddress = http://localhost:5178

GET {{NaserPortfolio.Api_HostAddress}}/api/v1/overview
Accept: application/json

###

GET {{NaserPortfolio.Api_HostAddress}}/api/v1/articles?language=fa
Accept: application/json

###

GET {{NaserPortfolio.Api_HostAddress}}/api/v1/articles/portfolio-workbench-case-study?language=en
Accept: application/json

###

GET {{NaserPortfolio.Api_HostAddress}}/health

###
